config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'background' => 'static_pages#background'

  get 'five_element_system' => 'static_pages#five_element_system'

  get 'fire' => 'five_elements#fire'

  get 'wood' => 'five_elements#wood'

  get 'earth' => 'five_elements#earth'

  get 'water' => 'five_elements#water'

  get 'metal' => 'five_elements#metal'

  get 'resources' => 'static_pages#resources'

  get 'contact' => 'static_pages#contact'

  get 'usage' => 'static_pages#usage'

  get 'tour1' => 'tour#page1'

  get 'tour2' => 'tour#page2'

  get 'tour3' => 'tour#page3'

  get 'tour4' => 'tour#page4'

  get 'signup' => 'users#new'

  get 'diagnosis' => 'diagnosis#new'

  get 'diagnoses' => 'diagnosis#new'

  post 'diagnoses' => 'diagnosis#create'

  get 'new_recommendation' => 'recommendations#new'

  get 'add_food' => 'foods#new'

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  delete 'logout' => 'session#destroy'

  get 'food_recommendation' => 'recommendations#show'

  get 'show_diagnosis' => 'diagnosis#show'

  resources :users

  resources :foods

  resources :recommendations

  resources :diagnosis

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    session[:current_page] = 'home'
  end

  def background
  end

  def five_element_system
  end

  def resources
  end

  def contact
  end

  def usage
  end

  def tour
  end

  def login
  end

  #Admin pages
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/background.html.erb
<div class='main-body-margin'>
  <div class='col-md-8 background-topheader'>
    Traditional Chinese Medicine: Principles
  </div>
  <div class='col-md-8'>
    <p class='background-text'>
    Chinese medicine focuses heavily on maintaining balance as the path to healthy living.  While extremes may be useful in the moment; ultimately, the strongest, healthiest state is one of balance. Stepping away from balance for too long leads to illness and chronic health problems.  As Harriet Beinfield says in "<em>Between Heaven and Earth.</em>"  Chinese medicine embraces the logic that the best remedy for calamity is to avert it - the best cure for sickness is prevention."  Maintaining balance is the way to prevent sickness or calamity from occurring.
    </p>
    <h1 class='background-header'>Yin and Yang <%= image_tag("yin-yang-glyph.png", class: 'glyph-left-margin') %></h1>
      <p class='background-text'>
        Yin and Yang are Chinese medicine's representation of opposition.  They describe opposite ends of the same spectrum, yet, cannot exist without one aother.  Without cold how would one describe heat, and without sound how would we know silence?  They are the opposite of one another, yet, each has the seed of its opposite within it, and balancing the qualities of Yin and Yang in the body is a central tenant of Chinese Medicine.
      </p>
    <h2 class='background-subheader'>Yin <%= image_tag("yin-glyph.png", class: 'glyph-left-margin') %></h2>
      <p class='background-text'>
        Yin, in Chinese medicine, is the representation of the passive, quiet side of some quality.  It's character in Chinese language originates as a depiction of the shady side of a mountain and describes calmer, cooler aspects of a spectrum, and can be realized in activities like mediation or yoga.
      </p>
    <h2 class='background-subheader'>Yang <%= image_tag("yang-glyph.png", class: 'glyph-left-margin') %></h2>
      <p class='background-text'>
        Opposite to Yin, Yang's representation is a characterization of the sunny side of a mountain.  Accordingly, Yang is the representation of activity and warmth.  Loudness, brightness, and energetic activities are associated with Yang qualities.
      </p>
    <h1 class='background-header'>Qi <%= image_tag("qi-glyph.png", class: 'glyph-left-margin') %></h1>
      <p class='background-text'>
        The Chinese character for Qi is a combination of the characters for air and rice, or the steam that pours off of hot rice.  Chinese medicine describeis Qi as the invisible energy which gives all life motion.  Life itself is Qi condensing, while death is its dispersal.  Qi is said to permeate all living things, and is what sustains one's life.  When Qi flows through one's system unimpeded their life force can be strong, while blockages in the flow of Qi can cause imbalance, weakness, and illness in an individual.
      </p>
    <h1 class='background-header'>Balance Through Food</h1>
      <p class='background-text'>
        According to Chinese medicine, all food contains various properties associated with Yin, Yang, Qi, and the five elements associated with the interconnected system central to Chinese medicine theory.  Some foods have been found to promote Yin qualities within the body, while others strengthen Yang aspect.  Other foods have been found to boost Qi circulation in the body.  As well, the flavors Chinese medicine uses in describing foods correlate with the five element system, and have been found to boost the corresponding element's properties within the body.  By understanding the effect foods have on each of these properties in one's body, a person can choose to eat foods which promote balance, health, and greater energy in that individual.
      </p>
  </div>

  <div class='col-md-3 col-md-offset-1'>
    <h2>Other background options:</h2>
    <%= button_to "5 Element System", five_element_system_path, class: 'elem-nav-button elem-general-color', method: "get" %>
    <%= button_to "Resources", resources_path, class: 'elem-nav-button elem-general-color', method: "get" %>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class='contact-main-body'>
  <div class='contact-title'>Contact us with any questions by email.</div>

  <div class='contact-header'>Email:</div>

  <div class='contact-body'>info@learningbalance.org</div>
</div>

app/views/static_pages/five_element_system.html.erb
<div class='main-body-margin'>
  <div class='row'>
    <div class='col-md-9 background-topheader'>
      The 5-Element System of TCM
    </div>
    <div class='col-md-9'>
      <div class='five-elem-text'>
        In addition to the Yin/Yang dichotomy, Chinese medicine desrcibes an interconnected system of five elements.  The relationships among these five elements of nourishment and regulation create an interweaved push and pull balance which is used to describe many aspects of life in Chinese medicine theory.  Around the outside of the five element system depicted below, in clockwise-order, each of the elements function to nourish the next element, and internally exists a pattern of regulation. (see the picture description for a more detailed explanation)   Associated with each of the elements are qualities which describe everything from personality traits to emotions to flavors of food. The flavors and colors associated with foods seen through the five element system play a major factor in achieving balance in diet in Chinese medicine.
      </div>
      </br>

      <div class='col-md-10 col-md-offset-1'>
        <div class='five-elem-info-box'>Click on any of the elements to learn more about it.</div>
      </div>

      <div class='col-md-11 col-md-offset-1'>
        <%= image_tag("TCM_5Elements.png", usemap: "#five_elem_circles", class: "five-elem-image") %>
      </div>
      </br>
    </div>
    <div class='col-md-3 col-md-offset-0'>
      <h2>Other background options:</h2>
      <div><%= button_to "Principles of TCM", background_path, class: 'elem-nav-button elem-general-color', method: "get" %></div>
      <div><%= button_to "Resources", resources_path, class: 'elem-nav-button elem-general-color', method: "get" %></div>
    </div>
  </div>
  <div class='col-md-10'>
    Wood is the fuel for Fire which produces ashes to return to the Earth which produce ores of Metal over time which can add beneficial properties to Water which nourishes the growth of Wood, completing the cycle.  Internally, Water regulates Fire which melts Metals, which binds or cuts Wood, which pierces and breaks up the Earth, which blocks and channels Water, completing the regulation cycle within the system.
  </div>
</div>

<map name="five_elem_circles">
  <area shape="circle" coords="345, 115, 110" href=<%= fire_path %> title="Learn about the Fire element" alt="Fire Element"/>
  <area shape="circle" coords="120, 280, 110" href=<%= wood_path %> title="Learn about the Wood element" alt="Wood Element"/>
  <area shape="circle" coords="560, 280, 110" href=<%= earth_path %> title="Learn about the Earth element" alt="Earth Element"/>
  <area shape="circle" coords="210, 525, 110" href=<%= water_path %> title="Learn about the Water element" alt="Water Element"/>
  <area shape="circle" coords="490, 525, 110" href=<%= metal_path %> title="Learn about the Metal element" alt="Metal Element"/>
</map>

app/views/static_pages/home.html.erb
<div class='welcome-main-body'>
  <div class='welcome-header'>
    Welcome to Learning Balance!
  </div>

  <div class='welcome-body'>
    This is a prototype for what will hopefully become a full-fledged food recommendation system based on the principles of Traditional Chinese Medicine.</br></br>
There wasn't enough to implement the full functionality as was hoped.</br>  Thanks, Obama.
  </div>
</div>

app/views/static_pages/resources.html.erb
<div class='main-body-margin'>
  <div class='row'>
  <div class='col-md-8'>
    <div class='background-topheader'>
      Resources used in creating this website.
    </div>
    </br>
    <div class='row'>
      <div class='col-md-3'><%= link_to image_tag("HelpingOurselves.png"), "http://www.redwingbooks.com/sku/HelOurGuiTra-E" %></div>
      <div class='col-md-9'>
        <div class='resource-title'>Helping Ourselves</div>
        <div class='resource-author'>by: Daverick Leggett</div></br>
        <div>Description:</div>
        <p>
Cras vel velit nunc. Phasellus a dapibus purus, id accumsan arcu. Aenean congue lacus non ante tristique commodo. Quisque mollis purus sit amet risus vestibulum, quis euismod nisl facilisis. Maecenas at lorem sed sem elementum porttitor. Sed sit amet ante tempus, dignissim nibh vel, ultrices lacus. Morbi eget tempor nulla. Etiam semper libero sit amet sapien mattis, vel mollis ipsum porta. Morbi convallis erat id ante consequat, quis faucibus arcu dapibus. 
        </p>
      </div>
    </div>
    </br>
    <div class='row'>
      <div class='col-md-3'><%= link_to image_tag("LiveInTheBalance.png"), "http://www.amazon.com/Live-Balance-Ground-Breaking-East-West-Nutrition/dp/1569246157/sr=8-1/qid=1166468591/ref=pd_bbs_sr_1/105-1845308-3952434?ie=UTF8&s=books"%></div>
      <div class='col-md-9'>
        <div class='resource-title'>Live in the Balance</div>
        <div class='resource-author'>by: Linda Prout</div></br>
        <div>Description:</div>
        <p>
Vestibulum volutpat dignissim magna, id suscipit velit ultrices at. Nunc vulputate consequat sem, maximus vulputate lorem rutrum quis. Nullam maximus, odio eu commodo aliquam, tellus enim consectetur velit, at faucibus ipsum nisl ultricies dui. Integer aliquam vel justo nec laoreet. Cras sagittis, enim non gravida condimentum, erat neque ullamcorper purus, a mollis mi justo vel turpis. Nunc eros velit, viverra et mattis eget, facilisis vel mauris. Donec lacinia massa quis pretium fringilla. Sed porttitor fringilla commodo. Sed luctus augue posuere gravida porttitor. Suspendisse potenti. Maecenas a dui arcu. Suspendisse eu sollicitudin odio. 
        </p>
      </div>
    </div>
    </br>
    <div class='row'>
      <div class='col-md-3'><%= link_to image_tag("TheChinaStudy.png"), "http://www.benbellavegan.com/book/the-china-study/" %></div>
      <div class='col-md-9'>
        <div class='resource-title'>The China Study</div>
        <div class='resource-author'>by: T. Colin Campbell</div></br>
        <div>Description:</div>
        <p>
Nunc nibh nisl, euismod ut arcu eget, pulvinar commodo lorem. Vestibulum sed feugiat odio. Vivamus cursus congue facilisis. Quisque id dui in elit accumsan venenatis. Ut mi turpis, eleifend sed neque id, feugiat lobortis nunc. Sed sed massa id erat hendrerit placerat ac id ex. Fusce vestibulum at orci non condimentum. Phasellus vestibulum enim felis, eget auctor metus sodales quis. 
        </p>
     </div>
    </div>
  </div>
  <div class='col-md-3 col-md-offset-1'>
    <h2>Other background options:</h2>
    <%= button_to "Principles of TCM", background_path, class: 'elem-nav-button elem-general-color', method: "get" %>
    <%= button_to "5 Element System", five_element_system_path, class: 'elem-nav-button elem-general-color', method: "get" %>
  </div>
  </br>
</div>

app/views/static_pages/usage.html.erb
<div class='usage-header'>
  Getting started
</div>
<div class='usage-text'>
  New users can obtain an automated diagnosis of any imbalance they may currently be experiencing.  It should be noted that, for the most accurate diagnosis, one should consult a professional practitioner of Chinese Medicine.  However, filling out the diagnosis checklist will point you in the right direction of any imbalance, and can help you get started planning meals based on your dietary "tilt".
</div>

<div class='usage-header'>
  Using your diagnosis
</div>
<div class='usage-text'>
  After obtaining a personal diagnosis of any imbalanced condition you will receive recommendations for foods that are best suited to return to balance for your personal imbalance.  As is typical with Chinese Medicine practices, choosing foods to eat to balance one's dietary tilt should take a moderate approach as opposed to extreme overloading to try and achieve balance as quickly as possible.  Pushing too heavily on any side of the spectrum can lead to further imbalance in the entire system.  Balance is best achieved by eating mostly balanced meals and including small amounts of the foods which match your dietary tilt in most meals.  A gradual approach to becoming balanced is the most stable path.
</div>

<div class='usage-header'>
  Food Recommender
</div>
<div class='usage-text'>
  This site also includes a recommender for foods that match any current condition you may be feeling: damp, cold, etc.  By clicking on the Recommend A Food button from your profile page, you can input values on various conditions, and the type of food you are craving, and you will receive a list of foods that can help balance your system in its current state.
</div>