config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'background' => 'static_pages#background'

  get 'five_element_system' => 'static_pages#five_element_system'

  get 'fire' => 'five_elements#fire'

  get 'wood' => 'five_elements#wood'

  get 'earth' => 'five_elements#earth'

  get 'water' => 'five_elements#water'

  get 'metal' => 'five_elements#metal'

  get 'resources' => 'static_pages#resources'

  get 'contact' => 'static_pages#contact'

  get 'usage' => 'static_pages#usage'

  get 'tour1' => 'tour#page1'

  get 'tour2' => 'tour#page2'

  get 'tour3' => 'tour#page3'

  get 'tour4' => 'tour#page4'

  get 'signup' => 'users#new'

  get 'diagnosis' => 'diagnosis#new'

  get 'diagnoses' => 'diagnosis#new'

  post 'diagnoses' => 'diagnosis#create'

  get 'new_recommendation' => 'recommendations#new'

  get 'add_food' => 'foods#new'

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  delete 'logout' => 'session#destroy'

  get 'food_recommendation' => 'recommendations#show'

  get 'show_diagnosis' => 'diagnosis#show'

  resources :users

  resources :foods

  resources :recommendations

  resources :diagnosis

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, :on => :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :skip_password_attribute, only: :update

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.current_login = Time.now
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    current_user.diagnosed = session[':new_diag']
    current_user.save
    redirect_to current_user
  end

  def show
    @user = User.find(params[:id])
    if @user.diagnosed != "None"
      if @user.diagnosed == "Yin Deficiency"
        @foods = Food.where("tonifies = 'Yin'")
      end
      if @user.diagnosed == "Yang Deficiency"
        @foods = Food.where("tonifies = 'Yang'")
      end
      if @user.diagnosed == "Qi Deficiency"
        @foods = Food.where("tonifies = 'Qi'")
      end
      if @user.diagnosed == "Blood Deficiency"
        @foods = Food.where("tonifies = 'Blood'")
      end
      if @user.diagnosed == "Internal Heat"
        @foods = Food.where("regulates = 'Heat'")
      end
      if @user.diagnosed == "Internal Cold"
        @foods = Food.where("regulates = 'Cold'")
      end
      if @user.diagnosed == "Internal Damp"
        @foods = Food.where("regulates = 'Damp'")
      end
      if @user.diagnosed == "Qi Stagnation"
        @foods = Food.where("regulates = 'Qi_Circulation'")
      end
      if @user.diagnosed == "Blood Stagnation"
        @foods = Food.where("regulates = 'Blood_Circulation'")
      end
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  def skip_password_attribute
    if params[:password].blank? && params[:password_validation].blank?
      params.except!(:password, :password_validation)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<ul class='foods'>
  <div class='row'>
    <li class='users-header'>
      <div class='col-md-6'>Name</div>
      <div class='col-md-3'>Last Login</div>
    </li>
  </div> 
  <% @users.order(:id).each do |user| %>
    <div class='row'>
      <li>
        <div class='col-md-6 users-item'><%= user.name %></div>
        <div class='col-md-3 users-item'><%= user.last_login %></div>
        <%= button_to "Delete User", user, method: :delete %>
      </li>
    </div>
  <% end %>    
</ul>

app/views/users/new.html.erb
<h1 class='col-md-offset-1'>Sign up for a new account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control login-input" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control login-input" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control login-input" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control login-input" %>

      <%= f.submit "Create new account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% require 'geoip' %>
<% require 'httparty' %>

<% @info = GeoIP.new(Rails.root.join("app/assets/lib/GeoLiteCity.dat")).city(request.remote_ip) %>

<div class='profile'>
  <h1>Profile for: <%= @user.name %></h1>

  </br>

  <% location_string = 'Could not be determined' %>
  <% temp_string = 'Could not be determined' %>

  <% if !@info.nil? %>
    <% if !@info.city_name.empty? %>
      <% location_string = @info.city_name + ', ' + @info.real_region_name %>
      <% url = 'http://api.wunderground.com/api/3a24e998cdf10373/conditions/q/' + @info.region_name + '/' + @info.city_name + '.json' %>
      <% response = HTTParty.get(url) %>
      <% if !response.parsed_response['current_observation'].nil? %>
        <% temp_string = response.parsed_response['current_observation']['temperature_string'] %>
      <% end %>
    <% end %>
  <% end %>

  <h2>Current Location: <%= location_string %></h2>
  <h2>Current Temperature: <%= temp_string %></h2>

  <%  season = nil %>
  <%  now = Time.now %>
  <% if (now.month <= 3 && now.day < 21) || (now.month == 12 && now.day >= 21) %>
    <% season = 'winter' %>
  <% elsif now.month <= 6 && now.day < 21 %>
    <% season = 'spring' %>
  <% elsif now.month <= 9 && now.day < 21 %>
    <% season = 'summer' %>
  <% else %>
    <% season = 'autumn' %>
  <% end %>

  <h2>Current season: <%= season %></h2>


  <div class='row'>
    <div class='col-md-6'>
      <% if @user.diagnosed == "None" %>
        <%= button_to "Obtain initial diagnosis", diagnosis_path, method: 'get', class: 'btn-lg' %>
      <% else %>
        <div class='diagnosis-display'>
          <%= "Diagnosis: " + @user.diagnosed %>
        </div>
        <div class='recommended-display'>
          Recommended foods to include with each meal:
        </div>
        <div class='recommended-foods-list-display'>
        <ul>
          <% @foods.each do |food| %>
            <%= food.name %>
          <% end %>
        </ul>
        </div>
        <%= button_to "Update diagnosis", diagnosis_path, method: 'get', class: 'btn' %>
      <% end %>
    </div>
    <div class='col-md-4 col-md-offset-0'>
      <%= button_to "Recommend A Food To Eat Now", new_recommendation_path, method: 'get', class: 'btn-lg' %>
    </div>
  </div>

  </br>

  <% if @user.last_login.nil? %>
    <h4>Welcome, <%= @user.name %>!</h4>
  <% else %>
    <h4>Last Login: <%= @user.last_login %></h4>
  <% end %>

</div>