config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'background' => 'static_pages#background'

  get 'five_element_system' => 'static_pages#five_element_system'

  get 'fire' => 'five_elements#fire'

  get 'wood' => 'five_elements#wood'

  get 'earth' => 'five_elements#earth'

  get 'water' => 'five_elements#water'

  get 'metal' => 'five_elements#metal'

  get 'resources' => 'static_pages#resources'

  get 'contact' => 'static_pages#contact'

  get 'usage' => 'static_pages#usage'

  get 'tour1' => 'tour#page1'

  get 'tour2' => 'tour#page2'

  get 'tour3' => 'tour#page3'

  get 'tour4' => 'tour#page4'

  get 'signup' => 'users#new'

  get 'diagnosis' => 'diagnosis#new'

  get 'diagnoses' => 'diagnosis#new'

  post 'diagnoses' => 'diagnosis#create'

  get 'new_recommendation' => 'recommendations#new'

  get 'add_food' => 'foods#new'

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  delete 'logout' => 'session#destroy'

  get 'food_recommendation' => 'recommendations#show'

  get 'show_diagnosis' => 'diagnosis#show'

  resources :users

  resources :foods

  resources :recommendations

  resources :diagnosis

end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      flash[:success] = "Success!"
      redirect_to new_food_path
    else
      render 'new'
    end
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    if @food.update_attributes(food_params)
      redirect_to foods_path
    else
      render 'edit'
    end
  end

  def show
    
  end

  def destroy
    Food.find(params[:id]).destroy
    redirect_to foods_path
  end

  private

    def food_params
      params.require(:food).permit(:name, :category, :flavor, :temperature, :tonifies, :regulates, :route)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/edit.html.erb
<h1 class='col-md-offset-1'>Edit Food</h1>
</br>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-2">
      <%= form_for (@food) do |f| %>
  
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :category %>
        <%= f.text_field :category, class: 'form-control' %>

        <%= f.label :flavor %>
        <%= f.text_field :flavor, class: 'form-control' %>

        <%= f.label :temperature %>
        <%= f.text_field :temperature, class: 'form-control' %>

        <%= f.label :tonifies %>
        <%= f.text_field :tonifies, class: 'form-control' %>

        <%= f.label :regulates %>
        <%= f.text_field :regulates, class: 'form-control' %>

        <%= f.label :route %>
        <%= f.text_field :route, class: 'form-control' %>

        </br>
        <%= f.submit 'Save changes', class: 'btn-primary, btn-lg' %>

      <% end %>
      </br>
      <%= button_to "Back to Food List", foods_path, method: 'get' %>
    </div>
  </div>
</div>

app/views/foods/index.html.erb
<div class='row'>
  <div class='col-md-2'><h1>All Foods</h1></div>
  <%= button_to 'Add New Food', new_food_path, method: 'get', class: 'col-md-offset-2 btn-lg' %>
</div>
<div class='container-fluid'>
  <ul class="foods">
      <h3>
        <div class='row'>
        <li>
          <div class='col-md-1'>Name</div>
          <div class='col-md-1'>Category</div>
          <div class='col-md-1'>Flavor</div>
          <div class='col-md-1'>Tonifies</div>
          <div class='col-md-2'>Regulates</div>
          <div class='col-md-3'>Route</div>
          <div class='col-md-1'>Temperature</div>
        </li>
        </div>
      </h3>
      </br>
      <% @foods.each do |food| %>
        <div class='row'>
        <li>
          <div class='col-md-1'><%= food.name %></div>
          <div class='col-md-1'><%= food.category %></div>
          <div class='col-md-1'><%= food.flavor %></div>
          <div class='col-md-1'><%= food.tonifies %></div>
          <div class='col-md-2'><%= food.regulates %></div>
          <div class='col-md-3'><%= food.route %></div>
          <div class='col-md-1'><%= food.temperature %></div>
          <div class='col-md-2'>
            <div class='row'>
              <div class='col-md-3 col-md-offset-3'><%= button_to "Edit", edit_food_path(food.id), method: :get %></div>
              <div class='col-md-3'><%= button_to "Delete", food, method: :delete %></div>
            </div>
          </div>
        </li>
        </div>
      <% end %>
  </ul>
</div>

app/views/foods/new.html.erb
<h1>Add New Food To Database</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-2">
      <%= form_for (@food) do |f| %>
  
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :category %>
        <%= f.text_field :category, class: 'form-control' %>

        <%= f.label :flavor %>
        <%= f.text_field :flavor, class: 'form-control' %>

        <%= f.label :temperature %>
        <%= f.text_field :temperature, class: 'form-control' %>

        <%= f.label :tonifies %>
        <%= f.text_field :tonifies, class: 'form-control' %>

        <%= f.label :regulates %>
        <%= f.text_field :regulates, class: 'form-control' %>

        <%= f.label :route %>
        <%= f.text_field :route, class: 'form-control' %>

        </br>
        <%= f.submit 'Add Food', class: 'btn-primary, btn-lg' %>

      <% end %>
      </br>
      <%= button_to "Back to Food List", foods_path, method: 'get' %>
    </div>
  </div>
</div>

app/views/foods/show.html.erb
This is where we would show the food.  How exciting!