config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'background' => 'static_pages#background'

  get 'five_element_system' => 'static_pages#five_element_system'

  get 'fire' => 'five_elements#fire'

  get 'wood' => 'five_elements#wood'

  get 'earth' => 'five_elements#earth'

  get 'water' => 'five_elements#water'

  get 'metal' => 'five_elements#metal'

  get 'resources' => 'static_pages#resources'

  get 'contact' => 'static_pages#contact'

  get 'usage' => 'static_pages#usage'

  get 'tour1' => 'tour#page1'

  get 'tour2' => 'tour#page2'

  get 'tour3' => 'tour#page3'

  get 'tour4' => 'tour#page4'

  get 'signup' => 'users#new'

  get 'diagnosis' => 'diagnosis#new'

  get 'diagnoses' => 'diagnosis#new'

  post 'diagnoses' => 'diagnosis#create'

  get 'new_recommendation' => 'recommendations#new'

  get 'add_food' => 'foods#new'

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  delete 'logout' => 'session#destroy'

  get 'food_recommendation' => 'recommendations#show'

  get 'show_diagnosis' => 'diagnosis#show'

  resources :users

  resources :foods

  resources :recommendations

  resources :diagnosis

end

app/views/layouts/_header.html.erb
<header>
  <div>
    <%= image_tag("healthy_foods1.png", height: '300px', :alt => "healthy food", id: 'img', class: 'center') %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearningBalance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body onload="startTimer()">
    <div class='top-image'>
      <%= render 'layouts/header' %>
    </div>
    <div class="nav-bar">
      <aside>
        <section>
          <h1>
            <ul class='nav-list'>
              <li><%= link_to "Welcome", root_url, class: 'navButton', method: 'get' %></li>
              <li id="drop" class="navButton">Background</li>
                <ul class="sub subNavBar">
                  <li><%= link_to "Principles of TCM", background_path, class: 'subNavButton' %></li>
                  <li><%= link_to "5 Element System", five_element_system_path, class: 'subNavButton' %></li>
                  <li><%= link_to "Resources", resources_path, class: 'subNavButton' %></li>
                </ul>
              <li><%= link_to "Contact us", contact_path, class: 'navButton', method: 'get' %></li>
              <% if logged_in? %>
                <li><%= link_to "Using This Site", usage_path, class: 'navButton', method: 'get' %></li>
                <li><%= link_to "Profile Page", current_user, class: 'navButton', method: 'get' %></li>
              <% else %>
              <% end %>
            </ul>
            <% if logged_in? %>
              </br>
            <% else %>
              <div class='nav-sign-in-style'><strong>Sign in:</strong></div>
            <% end %>
            <ul class='nav-list' id="menu-v">
              <% if logged_in? %>
                <li><%= link_to "Logout", logout_path, class: 'navButton', method: 'delete' %></li>
                <% if current_user.admin? %>
                  <div class='nav-admin-style'><strong>Admin:</strong></div>
                  <li><%= link_to "Foods", foods_path, class: 'navButton', method: 'get' %></li>
                  <li><%= link_to "Users", users_path, class: 'navButton', method: 'get' %></li>
                <% end %>
              <% else %>
                <li><%= link_to "Login", login_path, class: 'navButton', method: 'get' %></li>
                <li><%= link_to "New User", signup_path, class: 'navButton', method: 'get' %></li>
              <% end %>
            </ul>
          </h1>
        </section>
      </aside>
    </div>
    <div class='main-body'>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <%= yield %>
    </div>
</body>
</html>
<% #<li><%= link_to "Tour", tour1_path, class: 'navButton', method: 'get' %>